apiVersion: stackgres.io/v1beta1
kind: SGObjectStorage
metadata:
  namespace: asset-postgres-devuat
  name: azure-blob-backup
spec:
  type: 'azureBlob'
  azureBlob:
    bucket: 'postgres-backup-devuat'
    path: 
    azureCredentials:
      secretKeySelectors:
        storageAccount:
          name: azure-blob-storage-creds
          key: storage-account
        accessKey:
          name: azure-blob-storage-creds
          key: access-key